extends: default

ignore: |
  .devenv/
  .pre-commit-config.yaml
  node_modules/
  dist/
  .github/workflows/

rules:
  comments: disable
  document-start: disable
  line-length:
    max: 160
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
