name: 'Setup Wrangler'
description: 'Validate tracked wrangler.toml for CI builds'

inputs:
  mode:
    description: 'Build mode (dry-run or deploy)'
    required: false
    default: 'dry-run'

runs:
  using: 'composite'
  steps:
    - name: Validate wrangler.toml exists
      shell: bash
      run: |
        if [ ! -f wrangler.toml ]; then
          echo "❌ wrangler.toml is missing from repository root"
          exit 1
        fi
        echo "✅ Using tracked wrangler.toml for ${{ inputs.mode }}"
